<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>03_Promise的then方法</title>
    </head>
    <body>
        <script>
            /**
             * then：指定用于得到成功value的成功回调和用于得到失败reason的失败回调，并且将返回一个新的Promise实例化对象
             * 成功的状态：执行then方法的第一个回调含
             * 失败的状态：执行then方法的第二个回调含
             *
             * then方法的返回值的Promise实例化对象的状态取决于回调函数中的内容
             * 1-如果返回为非Promise实例化对象，则得到一个是成功的Promise
             * 2-如果返回的是Promise实例化对象，则Promise实例化对象的状态和结果值将直接影响result常量的状态和结果值
             * 3-如果未抛出异常，则新的Promise实例化对象(result)为失败的Promise
             */
            const pms1 = new Promise((resolve, reject) => {
                // 调整状态
                resolve("ok");
                // reject("error");
            });
            const result = pms1.then(
                (value) => {
                    /**
                     * [[PromiseState]] : "fulfilled"
                     * [[PromiseResult]] : undefined
                     */
                    console.log(value); // 【重点】情况1

                    // return value; // 情况1

                    // prettier-ignore
                    // return new Promise((resolve, reject) => { resolve("success"); }); // 情况2

                    // throw "异常信息"; // 情况3
                },
                (reason) => {
                    /**
                     * [[PromiseState]] : "fulfilled"
                     * [[PromiseResult]] : undefined
                     */
                    console.log(reason);
                    // 如果pms1执行了reject，会导致then里面的这里出现如上3种情况
                }
            );
            console.log(result);
        </script>
    </body>
</html>
